test: home-screen test completed
swent-group21/strive pull request #146
Opened 2024-11-14 17:42 UTC by Lil-Noe

This pull request includes several changes to improve the testing of UI components and end-to-end flows in the application. The updates include adding test IDs to various components, renaming test files for better organization, and adding new tests for the `HomeScreen` component.

### Test File Renaming and Imports:
* Renamed test files to `UI-tests` directory and updated import paths accordingly (`__tests__/UI-tests/Forgot-Password-test.tsx`, `__tests__/UI-tests/Sign-InScreen-test.tsx`, `__tests__/UI-tests/WelcomeScreens-test.tsx`). [[1]](diffhunk://#diff-199084a8fcdea20f4e6bbecf9b81bf0d68861ec04b78b9183c08a8d88caa990cL3-R3) [[2]](diffhunk://#diff-13f7cf78e1b5391bd6d0906c270a0d89731e418c0de1c11f293e7ee1a6ba78e8L3-R3) [[3]](diffhunk://#diff-c7711da46818f8bca7cb8d2ac4880c3e8893e7cad5616693ca27ef661e020ed7L3-R3)

### New Tests for `HomeScreen` Component:
* Added comprehensive tests for `HomeScreen` to check the rendering of `TopBar`, `BottomBar`, and `Challenge` components (`__tests__/UI-tests/HomeScreen-test.tsx`).

### Test IDs for Components:
* Added `testID` properties to `TopBar`, `BottomBar`, and `Challenge` components to facilitate testing (`components/TopBar.tsx`, `components/BottomBar.tsx`, `components/home/Challenge.tsx`). [[1]](diffhunk://#diff-c159ac41fdf79cb601137ef66682d7b8a5c08ce9d1bf1908fdca7b7c78935d69L24-R31) [[2]](diffhunk://#diff-158f4499a46466545a112c4a84574a4541ad86c5075c82fd2614da73248c5c4bL26-R33) [[3]](diffhunk://#diff-656f24095a4a5e4e4f6de57e74854903d91de22018bf248f283c50d5820b9874L36-R36)

### End-to-End Test for Navigation:
* Added an end-to-end test for navigating from the welcome screen to the sign-in screen, including mocking the `useRouter` hook from `expo-router` (`__tests__/e2e-tests/ForgottenPassword-test.tsx`).

### Additional Test IDs for Buttons:
* Added `testID` properties to `ThemedIconButton` and `ThemedTextButton` components to support the new tests (`components/theme/ThemedIconButton.tsx`, `components/theme/ThemedTextButton.tsx`). [[1]](diffhunk://#diff-e26226739699da0e7d5c38cfa314d2300fe0e111c8b7d4465672b5613bb63d16R13) [[2]](diffhunk://#diff-f2d109204fdad58bc26295e6c7253cdd9861645e91df591afdb87bbdcc7da60bR10)…vigation

2024-11-14 19:49 UTC, EduardoNeville requested changes
All in all it looks good,
There are a few minor changes such as path uniformity.
The routing question still remains.

2024-11-14 19:49 UTC, EduardoNeville commented on __tests__/UI-tests/Forgot-Password-test.tsx
> +import ForgotPasswordScreen from "../../app/screens/auth/forgot_password_screen";
Can we start using the @/app/screen ... syntax it will help avoid errors with path imports

2024-11-14 19:49 UTC, EduardoNeville commented on __tests__/UI-tests/HomeScreen-test.tsx
> +import HomeScreen from '@/app/screens/home/home_screen';
well done. Please maintain this path structure

2024-11-14 19:49 UTC, EduardoNeville commented on __tests__/UI-tests/Sign-InScreen-test.tsx
> +import SignInScreen from "../../app/screens/auth/sign_in_screen";
same as the comment as __tests__/UI-tests/Forgot-Password-test.tsx

2024-11-14 19:49 UTC, EduardoNeville commented on __tests__/UI-tests/WelcomeScreens-test.tsx
> +import WelcomeScreens from "../../app/index";
same goes here as in the comment of this file: __tests__/UI-tests/Forgot-Password-test.tsx

2024-11-14 19:49 UTC, EduardoNeville commented on __tests__/e2e-tests/ForgottenPassword-test.tsx
> +import WelcomeConceptScreen from '@/app/screens/welcome/final_screen';
well done follow this structure

2024-11-14 19:49 UTC, EduardoNeville commented on __tests__/e2e-tests/ForgottenPassword-test.tsx
> +jest.mock('expo-router', () => ({
Will this be the same if we change the router? We'll have to change it if the routing mechanism changes

2024-11-14 19:49 UTC, EduardoNeville commented on __tests__/e2e-tests/ForgottenPassword-test.tsx
> +  const mockRouter = {
We'll have to create a different mock but this one works for now

2024-11-14 19:49 UTC, EduardoNeville commented on __tests__/e2e-tests/ForgottenPassword-test.tsx
> +    const finalButton = getByText('Login');
try adding an id instead just in case

2024-11-14 19:49 UTC, EduardoNeville commented on app/index.tsx
> +        testID="welcome-scrollview"
just like this well done

2024-11-14 19:49 UTC, EduardoNeville commented on app/screens/welcome/final_screen.tsx
> +    <ThemedView style={styles.container} testID="welcome-final-screen">
perfect

2024-11-14 19:57 UTC, Roman-batut requested changes
Overall your implementation is very good, I would advise you to rebase your branch by merging master into it and remove notably the _test_id_ declarations in _ThemedIconButton_ and _ThemedTextButton_ as they're covered by most recent version of master. Also as you're modifying some lines in the screen this will avoid having lots of merge conflicts later on.

2024-11-14 19:57 UTC, Roman-batut commented on __tests__/UI-tests/Forgot-Password-test.tsx
> +import ForgotPasswordScreen from "../../app/screens/auth/forgot_password_screen";
You could probably use @ instead of ../..

2024-11-14 19:57 UTC, Roman-batut commented on __tests__/UI-tests/Sign-InScreen-test.tsx
> +import SignInScreen from "../../app/screens/auth/sign_in_screen";
Same you can use @ here

2024-11-14 19:57 UTC, Roman-batut commented on __tests__/UI-tests/WelcomeScreens-test.tsx
> +import WelcomeScreens from "../../app/index";
Use @ instead of ../..

2024-11-14 19:57 UTC, Roman-batut commented on __tests__/e2e-tests/ForgottenPassword-test.tsx
Some consts you declare are only used once, maybe it would be better for conciseness not to declare them and add a comment that says what's going on just as you have right now.

2024-11-14 19:57 UTC, Roman-batut commented on components/theme/ThemedIconButton.tsx
> +  testID?: string;
Actually you don't need this as one the last PR to master's branch implements this by extending ThemedIconButtonProps with IconProps.

2024-11-14 19:57 UTC, Roman-batut commented on components/theme/ThemedTextButton.tsx
> +  testID?: string;
Same as in ThemedIconButton

2024-11-14 22:14 UTC, Roman-batut approved these changes
You incorporated the changes requested, well done.
LGTM

2024-11-15 09:28 UTC, Tristan-C789 commented
You addressed the issues successfully! Solve the merge conflict and we'll merge into main.

2024-11-20 16:56 UTC, Roman-batut requested changes
Overall you need to merge master into your branch to take the latest version into account as well as use testIDs instead of texts. Also try to implement the tests you commented when the jest-config will be correctly implemented.

2024-11-20 16:56 UTC, Roman-batut commented on __tests__/UI-tests/HomeScreen-test.tsx
You might want to test the display of more components for the test to be complete, there are the comments components (text input) as well as the like button.

2024-11-20 16:56 UTC, Roman-batut commented on __tests__/UI-tests/Sign-InScreen-test.tsx
Same as the Maximize screen test.

2024-11-20 16:56 UTC, Roman-batut commented on __tests__/UI-tests/Sign-UpScreen-test.tsx
Same as the Maximize screen test.

2024-11-20 16:56 UTC, Roman-batut commented on __tests__/UI-tests/WelcomeScreens-test.tsx
We may want to test by testId as said previously although this is arguable as these are text components. However if we wanna change the text by something else or even slightly modify it we'll need to change the tests as well, which isn't practical

2024-11-20 16:56 UTC, Roman-batut commented on __tests__/e2e-tests/ForgottenPassword-test.tsx
Same as the Maximize screen test.

2024-11-20 16:56 UTC, Roman-batut commented on app/screens/auth/forgot_password_screen.tsx
I see here your version of forgot_password_screen uses useRouter though the latest version of master uses a centralized navigation stack. I would advise you to merge master into your branch to get the latest version and not encounter big merge conflicts at the end.

2024-11-20 16:56 UTC, Roman-batut commented on components/navigation/BottomBar.tsx
This is a good implementation, indeed BottomBar didn't have any testID attached to it. Bravo !

2024-11-20 16:56 UTC, Roman-batut commented on components/navigation/TopBar.tsx
Same as BottomBar, very elegant way of implementing the testIDs inside its contained elements.

2024-11-21 19:55 UTC, closed without merging