Feat/current challenge description
swent-group21/strive pull request #185
Opened 2024-11-25 14:01 UTC by margdsq

This pull request includes several significant updates to the `home` screen and related components, focusing on adding new features and improving the existing ones. The most important changes include the addition of a `Timer` component, a `NumberCard` component, and a `ChallengeDescription` component, along with corresponding tests and updates to the `FirestoreCtrl` for fetching challenge descriptions.

### New Components and Features:

* **Timer Component:**
  - Added a `Timer` component that displays the time remaining until a specified end date, with updates every second.
  - Includes tests to verify correct behavior for various time intervals and the `onTimerFinished` callback.

* **NumberCard Component:**
  - Added a `NumberCard` component to display numbers with specific formatting (e.g., zero-padded single digits).
  - Includes tests to verify correct rendering for different number inputs.

* **ChallengeDescription Component:**
  - Added a `ChallengeDescription` component to display the current challenge's title, description, and a timer until the challenge's end date.

### Home Screen Updates:

* **Home Screen Integration:**
  - Integrated the `ChallengeDescription` component into the `HomeScreen` and added logic to fetch the current challenge description from Firestore. [[1]](diffhunk://#diff-6526ae8a24a7d12b3c578f5add3c25b6adff57eec7ca6c7c8010da92c01e1b59R11-R51) [[2]](diffhunk://#diff-6526ae8a24a7d12b3c578f5add3c25b6adff57eec7ca6c7c8010da92c01e1b59L40-R82)

### Firestore Controller Updates:

* **Firestore Data Fetching:**
  - Added a method in `FirestoreCtrl` to retrieve the current challenge description from Firestore.
  - Defined a new `DBChallengeDescription` type to structure the challenge description data.

### Dependency Updates:

* **Package.json:**
  - Added `@react-navigation/native-stack` dependency to the project.

2024-11-25 19:47 UTC, Lil-Noe requested changes
You added some great features that make sense, thank you for that ! Make sure to follow the conventions of the project but it's a good job.

2024-11-25 19:47 UTC, Lil-Noe commented on __tests__/UI-tests/Number-Cards-test.tsx
I think it would be better to use getByTestId to retrieve elements instead of getByText, to specify they are tested when looking in the component directly. To do this you can use dynamic testIds.

2024-11-25 19:47 UTC, Lil-Noe commented on __tests__/UI-tests/Timer-test.tsx
Same here, would be better to use getByTestId. Furthermore I think these would be unit tests instead of UI-tests even if you render components, as you test different situations.

2024-11-25 19:47 UTC, Lil-Noe commented on __tests__/UI-tests/__snapshots__/Number-Cards-test.tsx.snap
When do you use this snapshot ? In which context ?

2024-11-25 19:47 UTC, Lil-Noe commented on app/screens/home/home_screen.tsx
> +    });
There is confusion between the const challenges and this new const currentChallenge, maybe you should rename one of them.

2024-11-25 19:47 UTC, Lil-Noe commented on components/home/Challenge_Description.tsx
This is actually really useful in the scope of the app ! Good job.

2024-11-26 09:13 UTC, margdsq commented on __tests__/UI-tests/__snapshots__/Number-Cards-test.tsx.snap
It was for a previous test, I'll remove it.

2024-11-29 02:37 UTC, Lil-Noe approved these changes
I see you addressed the issues that were raised so thank you for that !

2024-11-29 02:37 UTC, merged